version: '3'
services:
  sibkov-php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_USER_GID=${HOST_USER_GID}
    ports:
      - '${PHP_CLI_XDEBUG_HOST_PORT}:9003'
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    environment:
      PHP_IDE_CONFIG: 'serverName=sibkov.docker'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - 'cli-tools'        # the profile is needed in order not to start this service with "docker compose up" command
  sibkov-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_HOST_PORT}:80'
    volumes:
      - .:/app
    depends_on:
      - sibkov-php-fpm
    restart: always
  sibkov-php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_USER_GID=${HOST_USER_GID}
    volumes:
      - .:/app
  sibkov-nodejs-cli:
    build:
      context: ./docker/nodejs-cli
      dockerfile: Dockerfile
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_USER_GID=${HOST_USER_GID}
    volumes:
      - .:/app
    profiles:
      - 'cli-tools'        # the profile is needed in order not to start this service with "docker compose up" command
volumes:
  composer:
