version: '3'
services:
  sibkov-php-cli:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    environment:
      PHP_IDE_CONFIG: 'serverName=crk-sibkov.docker'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - 'cli-tools'        # the profile is needed in order not to start this service with "docker compose up" command
  sibkov-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '${NGINX_HOST_PORT}:80'
    volumes:
      - .:/app
  sibkov-php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - .:/app
  sibkov-node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
volumes:
  composer:
